### ISSUE TITLE
Leak ring.reloader() goroutine on every new LoadRing

### ISSUE THREAD

**Issue by corystone** [troubling/hummingbird#111]
This gets called by NewProxyDirectClient in ServeHTTP, so we're leaking them pretty quickly.

**Comment by corystone** [comment]
goroutine 745 [sleep]:
time.Sleep(0x37e11d600)
        /usr/local/go/src/runtime/time.go:59 +0xf9
github.com/troubling/hummingbird/common/ring.(*hashRing).reloader(0xc4203996e0, 0x1c, 0x1c)
        /home/cory/go/src/github.com/troubling/hummingbird/common/ring/ring.go:265 +0x30
created by github.com/troubling/hummingbird/common/ring.LoadRing
        /home/cory/go/src/github.com/troubling/hummingbird/common/ring/ring.go:329 +0x14c
