### ISSUE TITLE
Sub Command "capabilities" isn't implemented

### ISSUE THREAD

**Issue by letterj** [troubling/hummingbird#147]
swift -A http://humbird2:5000/v3 --auth-version 3 --os-project-name service -U swift -K password capabilities
Traceback (most recent call last):
File "/usr/bin/swift", line 10, in 
sys.exit(main())
File "/usr/lib/python2.7/dist-packages/swiftclient/shell.py", line 1477, in main
globals()['st_%s' % args[0]](parser, argv[1:], output)
File "/usr/lib/python2.7/dist-packages/swiftclient/shell.py", line 997, in st_capabilities
_print_compo_cap('Core', {'swift': capabilities['swift']})
KeyError: u'swift'

**Comment by letterj** [comment]
Duplicate
